FROM python:3.10-slim

RUN pip install --no-cache-dir mlflow==2.12.2

WORKDIR /app

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:////mlruns/mlflow_ui.db", "--default-artifact-root", "/mlruns/artifacts", "--host", "0.0.0.0", "--port", "5000"]